import sys
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import IUPAC
from random import randint, choice

def main(size):

    random_seq = generate_random_sequence(size)

    record = [SeqRecord(Seq(random_seq), id=str(randint(0,sys.maxsize)), name='RandomSeq',
                       description='random dna sequence generated by generate_random_sequence.py')]

    SeqIO.write(record, sys.stdout, "fasta")


def generate_random_sequence(size):
    nucs = ['A','C','G','T']
    seq = ""
    for i in range(size):
        seq += choice(nucs)
    return(seq)

if __name__ == '__main__':
    size = int(sys.argv[1])

    main(size)